### ISSUE TITLE
Uncaught in promise error

### ISSUE THREAD

**Issue by ctbritt** [chrisk123999/chris-premades#22]
Getting this error whenever I load foundry. Doesn't seem to affect anything, but just FYI: 
```
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'startsWith')
[Detected 1 package: chris-premades]
    at _parseUuid (foundry.js:4176:13)
    at fromUuid (foundry.js:4122:49)
    at loadTriggers (movement.js:12:36)
    at Object.fn (module.js:41:8)
```

Seems to be this line in `movement.js`: 
```
                let effect = await fromUuid(spell.effectUuid)
```

**Comment by chrisk123999** [comment]
Open console in your game and type the following command in:
`chrisPremades.tokenMove.purge()`
