### ISSUE TITLE
Protection from Evil and Good F12 Error

### ISSUE THREAD

**Issue by omega605** [chrisk123999/chris-premades#29]
Protection from Evil and Good is not applying disadvantage to the attack roll against the protected target:  If more information is needed please let me know!

midi-qol.js:24 midi-qol |  hooked function for hook midi-qol.preambleComplete threw  TypeError: Cannot read properties of null (reading 'getFlag')
    at Object._handleASEPreamble [as fn] (setup.js:25724:30)
    at async asyncHooksCall (utils.js:3652:21)
    at async Workflow._next (workflow.js:351:9)
    at async Workflow.next (workflow.js:262:10)

midi-qol.js:24 midi-qol |  hooked function for hook midi-qol.preCheckSaves threw  TypeError: Cannot read properties of null (reading 'getFlag')
    at Object._preCheckSaves [as fn] (setup.js:25691:30)
    at async asyncHooksCallAll (utils.js:3631:4)
    at async Workflow._next (workflow.js:590:6)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)

**Comment by MotoMoto1234** [comment]
Remove ASE

**Comment by chrisk123999** [comment]
As @MotoMoto1234 has said, could you disable ASE and see if the issue persists?  If disabling ASE fixes it, I'll see what can be done.

**Comment by omega605** [comment]
I did remove ASE as a module, refreshed, etc...The F12 and errors have cleared, however; there is a warning: 
itemhandling.js:447 testing: advantage/disadvantage {}
I did check to make sure that all required modules where installed.  Thank you for the help, this module is awesome and has tons of potential.

**Comment by chrisk123999** [comment]
You can ignore that last warning.  That's just leftover debugging code in Midi-Qol.
