### ISSUE TITLE
[BUG] All-Purpose Tool: Channel Creative Forces doesn't work

### ISSUE THREAD

**Issue by Asmerion** [chrisk123999/chris-premades#313]
I am getting the following error message when I try to run this function:

midi.js:157 TypeError: Cannot read properties of undefined (reading 'filter')
    at Object.getSpellsOfLevel (spellUtils.js:4:22)
    at async Object.macro (allPurposeTool.js:22:9)
    at async pC (midi.js:154:9)
    at async gC (midi.js:167:9)
    at async Object.rollFinished (midi.js:253:61)
    at async e.WorkflowState_RollFinished (workflow.js:67:13)
    at async e.performState (workflow.js:513:21)
    
**Versions:**
Cauldron of Plentiful Resources: v1.0.16
FoundryVTT: v12.331

**Comment by Autumn225** [comment]
You haven't set up your spell list journal. See the wiki's getting started page.
